### PR TITLE
Unicode input

### PR DESCRIPTION
**Pull request by novas0x2a**
This solves the input side of #92, in that it is now safe to provide unicode strings to Text fields, and they will be correctly encoded to utf-8 bytes.

Output side is a bit trickier, obviously :)

### CODE REVIEW

**Comment by novas0x2a** [comment]
Hm. Any idea what's up with that pypy failure? I don't know pypy very well, but on my machine that test passes (with pypy 4.0.1)

**Comment by jparyani** [comment]
It appears travis is working with a quite old version of pypy (v2.6.1). It passes locally for me (also v4.0.1), so I'm ok with marking the test as skipped on pypy for now.

**Comment by treeandbrick** [comment]
Should this have been merged without support for unicode output?  As it is now, roundtrips won't work. You pass in unicode, and it is saved as utf8. When you read it back, you get utf8 bytes, not unicode. This seems undesirable.

If you accept that all `capnp::Text` should be represented as unicode, then the fix for Python 2.x with respect to unicode output is pretty simple, though I didn't do a thorough check. In `to_python_reader` and `to_python_builder`, decode from utf8.  In `_StructModule`, you also need to encode the name as utf8. Finding a solution that works simultaneously for 2 and 3 may require more work.

**Comment by novas0x2a** [comment]
> Should this have been merged without support for unicode output? As it is now, roundtrips won't work. You pass in unicode, and it is saved as utf8. When you read it back, you get utf8 bytes, not unicode. This seems undesirable.

It's not awesome, to be sure, but the previous state would throw an exception when you stored unicode, so this pull is better than not having it.

> Finding a solution that works simultaneously for 2 and 3 may require more work.

Yeah, that was the problem I had (that I haven't had the time to solve yet)- I'm not the maintainer, but perhaps if you have time...

**Pull request merged**
