### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by diorcety**
Rework dynamicfield getter and setter. Provide a way to intercept this method (usefull for changing or extending the default from_dict to_dict)

### CODE REVIEW

**Comment by jparyani** [comment]
While the idea behind these changes are really good, I don't think I can merge the PR as-is (and I'm not sure it's fixable). These changes have huge performance implications. Now every access of a field will incur multiple levels of indirection, and will even call into python functions, taking us out of fast C-land.

You can run `benchmark/bin/pycapnp-carsales object no-reuse none 100` to see a quick micro-benchmark. The results I got were almost exactly 10x slower:

Your branch:
```
time benchmark/bin/pycapnp-carsales object no-reuse none 100
benchmark/bin/pycapnp-carsales object no-reuse none 100  6.71s user 0.01s system 99% cpu 6.722 total
```
HEAD:
```
time benchmark/bin/pycapnp-carsales object no-reuse none 100
benchmark/bin/pycapnp-carsales object no-reuse none 100  0.60s user 0.02s system 99% cpu 0.622 total
```

Instead, to achieve much of the same functionality, I'd rather do what was described in #107 with mixin classes allowing users can add whatever custom methods they desire at a higher level, instead of messing with field accessors.

**Comment by diorcety** [comment]
Indeed, that seems huge, maybe there is something i did wrong too...

**Comment by diorcety** [comment]
Okay, i tried to improve that. I succeed to reach 0.70s changing some stuff, for example def to cpdef ... The issue now even with the cpdef, if i redifine the function, the new function is not called ... i supposed to work...

**Comment by diorcety** [comment]
Finally ! I fixed this issue withCython.Compiler.Options.lookup_module_cpdef = True
Here the same stuff but optimized. I'm now near 0.80 for the same test. Maybe there is some other cython tricks to improve that, but i'm a newbie in cython.

**Comment by jparyani** [comment]
Sorry, I let this languish, but I was considering what to do with it.

I'm sorry to say, but I'm still not comfortable accepting this PR. There's still a sizable performance hit (around a 33% slowdown in my testing), and even disregarding that, it feels like this feature doesn't need to be implemented at such a low level. I'd much rather have a high level API where you can define custom methods for pycapnp structs, and do things like overriding to/from_dict.

There's definitely some good parts to this PR (like refactoring `_to_python_reader`), but as-is I won't be merging it.

**Comment by diorcety** [comment]
OK. No problem

**Pull request closed without merging**
