### PR TITLE
Let TwoParty Clients and Servers take ReaderOptions

### PR DESCRIPTION
**Pull request by asilversempirical**
This is the pycapnp equivalent of https://github.com/sandstorm-io/capnproto/pull/120.

Fixes https://github.com/jparyani/pycapnp/issues/125

### CODE REVIEW

**Comment by asilversempirical** [comment]
I pulled out a helper to create ReaderOptions since the initialization was duplicated in a bunch of places, but I can revert that if you'd prefer.

**Comment by jparyani** [comment]
This is a great change (and even had tests!). Thanks for submitting this, and sorry for not getting to it til now.

**Comment by asilversempirical** [comment]
Thanks! (And welcome back :))

Were you planning a PyPI release as well including the recent changes? This would be really nice to land, since it's a pain to work around without the fix.

**Comment by jparyani** [comment]
I'll do a release later tonight.

**Comment by jparyani** [comment]
New release is up now

**Comment by asilversempirical** [comment]
Great, thank you!

**Pull request merged**
